# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4208a03420fb563de52117343c62e4ca8e15c438d85fe9aa42978a01d507ccfc25b8badd706f3ef10bd3746694f6e94024ab1785e08e6b734552bd2cb3b9a306

test:
  secret_key_base: 46a61c01b381d06573295ab1349b23023e7a6ac3256de2b558cb983d7b38479a40dc5339084572d5ababe68327d9bcaf8c4035a2b6e3d26ec994f456b5cc6b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
